# Dev version
FROM node:22.0

WORKDIR /app

# Копируем package.json и package-lock.json (если есть)
COPY package.json package-lock.json* ./

# Устанавливаем зависимости
RUN npm install

# Копируем весь проект
COPY . .


# Запускаем dev-сервер
CMD ["npm", "run", "dev"]