services:
  db:
    image: postgres:17-alpine
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - private_django
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    entrypoint: /entrypoint.sh
    command: bash -c "gunicorn backend.wsgi:application --bind 0.0.0.0:${DJANGO_PORT}"
    working_dir: /app/backend
    restart: on-failure
    volumes:
      - ./backend:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.prod
    depends_on:
      db:
        condition: service_healthy
    networks:
      - private_django
      - public_network

  redis:
    image: redis:7
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data
    networks:
      - private_django

  nginx:
    container_name: core_web
    image: nginx:stable-alpine
    restart: on-failure
    ports:
      - "${NGINX_PORT}:${NGINX_INTERNAL_PORT}"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/staticfiles
      - media_volume:/app/media
    networks:
      - private_django
      - public_network

volumes:
  postgres_data:
  media_volume:
  static_volume:
  redis_data:

networks:
  public_network:
    driver: bridge
  private_django:
    internal: true
