# Generated by Django 5.1.1 on 2025-10-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.CharField(max_length=255, verbose_name='Адресс')),
                ('apartment', models.CharField(blank=True, max_length=50, null=True, verbose_name='Квартира')),
                ('entrance', models.CharField(blank=True, max_length=50, null=True, verbose_name='Подъезд')),
                ('floor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Этаж')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Наличными'), ('card_online', 'Картой онлайн'), ('card_on_delivery', 'Картой при получении')], max_length=50, verbose_name='Оплата')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('preparing', 'Готовится'), ('delivering', 'Доставляется'), ('delivered', 'Доставлено'), ('cancelled', 'Отменен')], default='pending', max_length=50, verbose_name='Статус')),
                ('summary', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товар',
            },
        ),
    ]
