FROM python:3.12-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        gdal-bin \
        binutils \
        libproj-dev \
        libgdal-dev \
        netcat-openbsd \
        postgresql-client \
        dos2unix \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip install poetry

WORKDIR /app

COPY pyproject.toml poetry.lock ./

RUN poetry config virtualenvs.create false && \
    poetry install --no-interaction --no-ansi --no-root

COPY entrypoint.sh /entrypoint.sh
RUN dos2unix /entrypoint.sh && chmod +x /entrypoint.sh

COPY . .

RUN ls -la /entrypoint.sh && which python